options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: kabaddi-backend

steps:
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/kabaddi-backend:$SHORT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/kabaddi-backend:latest',
      '.'
    ]
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kabaddi-backend:$SHORT_SHA']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kabaddi-backend:latest']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        
        # Set environment variables for deployment using Cloud SQL
        # Using a different variable name to avoid substitution conflicts
        DB_CONNECTION_STRING="postgresql://user:Kabaddiguru@123@/kabaddi_data?host=/cloudsql/kabaddiguru:us-central1:kabaddi-sql"
        JWT_SECRET_KEY="your-secret-key-here"
        FRONTEND_ORIGIN="https://kabaddi-frontend-324578194548.us-central1.run.app"
        GOOGLE_API_KEY="AIzaSyDMW0sn3dOuAMMupZS0rkb5MP_bAqBpgtc"
        GEMINI_MODEL="gemini-2.5-flash-preview-05-20"
        DEBUG="false"
        
        gcloud run deploy kabaddi-backend \
          --image gcr.io/$PROJECT_ID/kabaddi-backend:$SHORT_SHA \
          --region "$_REGION" \
          --platform managed \
          --allow-unauthenticated \
          --port 8000 \
          --memory 2Gi \
          --cpu 2 \
          --max-instances 10 \
          --add-cloudsql-instances kabaddiguru:us-central1:kabaddi-sql \
          --set-env-vars DATABASE_URL="$DB_CONNECTION_STRING",JWT_SECRET_KEY="$JWT_SECRET_KEY",FRONTEND_ORIGIN="$FRONTEND_ORIGIN",GOOGLE_API_KEY="$GOOGLE_API_KEY",GEMINI_MODEL="$GEMINI_MODEL",DEBUG="$DEBUG"

images:
  - 'gcr.io/$PROJECT_ID/kabaddi-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/kabaddi-backend:latest'
